# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('order', models.IntegerField(default=0)),
                ('special', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, editable=False, null=True)),
                ('short_desc_html', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'verbose_name': 'Service',
                'ordering': ['order', 'title'],
            },
        ),
    ]
