# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
