# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='short_desc_html',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
