# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('show', models.BooleanField(default=True)),
                ('program_choices', models.CharField(choices=[('always', 'Program/Service '), ('summer', 'Summer Programs'), ('fall', 'Fall Programs'), ('winter', 'Winter Programs'), ('spring', 'Spring Programs')], default='Chrome', max_length=8, verbose_name='Program Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, editable=False, null=True)),
                ('short_desc_html', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'verbose_name': 'Program',
                'ordering': ['order', 'title'],
            },
        ),
    ]
