# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=1024)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
