# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(default='Resource Name', max_length=128)),
                ('contact_name', models.CharField(default='', max_length=64)),
                ('email', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=256)),
                ('phone_href', models.CharField(default='', max_length=256)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['order', 'resource_name'],
            },
        ),
    ]
